site:
  title: The Internals of Delta Lake
  url: https://delta.japila.pl
  start_page: delta::index.adoc
  keys:
      google_analytics: 'UA-151208281-1'
  robots: allow

content:
  sources:
    - url: .
      branches: HEAD
      start_path: .

runtime:
  cache_dir: .out/cache

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    sectlinks: ''
    linkattrs: ''

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"

output:
  dir: .out/local
  clean: true
