site:
  title: The Internals Of Delta Lake (Local)
  url: https://books.japila.pl/delta-lake-internals
  start_page: delta::index.adoc
  keys:
      google_analytics: 'UA-151208281-1'
  robots: allow
content:
  sources:
    - url: .
      branches: HEAD
      start_path: .
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    sectlinks: ''
    linkattrs: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
output:
  dir: .out/local
runtime:
  cache_dir: .out/cache
